version: "3.8"
services:
  web:
    build: .
    command: yarn start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      pg_host: postgres
      redis_host: redis

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ticketdo"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
