import axios from "axios";
export type EsewaPaymentVerificationParams = {
  amt: number;
  rid: string;
  id: string;
  scd: string;
  /**
   * @example
    {
    amt: 100,
    rid: "000AE01",
    pid: "ee2c3ca1-696b-4cc5-a6be-2c40d929d453",
    };
   */
};

const scd = "EPAYTEST";

export type EsewaPaymentInitiationParams = {
  amt: number;
  psc: number;
  pdc: number;
  pid: string; //product id
  txAmt: number;
  tAmt: number;

  /**
    * @example 
    * {
        amt: 100,
        psc: 0,
        pdc: 0,
        txAmt: 0,
        tAmt: 100,
        pid: "ee2c3ca1-696b-4cc5-a6be-2c40d929d453",
    }
    */
};

/**
 * Esewa payment initiation is done from here
 * If successful payment occurs
 * the user is redirected to success url with following response in url params
    oid	Product ID (pid) used on payment request
    amt	Total payment amount (tAmt)
    refId	A unique payment reference code generated by eSewa
@example http://merchant.com.np/page/esewa_payment_success?q=su&oid=ee2c3ca1-696b-4cc5-a6be-2c40d929d453&amt=100&refId=000AE01

* Failure will result in failure_url redirection 
@example http://merchant.com.np/page/esewa_payment_failure
 * @param data 
 */

export const EsewaPaymentInitiation = async (data: EsewaPaymentInitiationParams) => {
  const restParams = {
    scd: "EPAYTEST",
    su: process.env.esewa_success_url,
    fu: process.env.esewa_failed_url,
  };
  return await axios.post("https://uat.esewa.com.np/epay/main", {
    ...data,
    restParams,
  });
};

export const EsewaPaymentVerification = async (data: EsewaPaymentVerificationParams) => {
  const restParams = {
    scd,
  };
  return await axios.post("https://uat.esewa.com.np/epay/transrec", {
    ...data,
    restParams,
  });
};
